databases:
  - name: mysitevideo
    databaseName: mysitevideo
    user: mysitevideo

services:
  - type: web
    name: mysitevideo
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn mysitevideo.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: mysitevideo
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4